import type { TemplateInput } from "../schema";
import { fields } from "./fields";

/**
 * Story templates (v2.0.0): one scrolling page of chapters with games,
 * photos, a letter and a finale. Each has its own look, games and copy.
 * Published versions are immutable: add a new version to change one.
 */

const base = { version: "2.0.0", occasion: "birthday", currency: "INR" as const, layout: "story" as const, scenes: [] };
const PHOTOS = { min: 4, max: 8 };

const REASONS = [
  "The way your whole face changes when you laugh.",
  "You remember the little things nobody else does.",
  "You make ordinary days feel like plans.",
  "You are kind even when nobody is watching.",
  "You never let me give up on myself.",
  "Life is simply better with you in it.",
];

export const STORY_TEMPLATES: TemplateInput[] = [
  /* 1 ─────────────────────────────── */
  {
    ...base,
    slug: "bday-starlit-love",
    name: "Starlit Love",
    description: "A night sky full of balloons, a question with only one right answer, games, polaroids and a letter that types itself.",
    traits: ["For a partner", "Catch-the-hearts game", "Spin the wheel", "Fireworks finale"],
    priceMinor: 29900,
    theme: {
      bg: "#12071a", fg: "#fbe4ee", muted: "#d7b9cb", line: "#3a2046", card: "#1f0d29",
      accent: "#ff5c8a", accent2: "#c792ff", accent3: "#ffc95e", onAccent: "#2a0b18", paper: "#fff7f0", paperInk: "#3a1428",
      display: "'Fraunces', Georgia, serif", hand: "'Great Vibes', cursive", body: "'Outfit', system-ui, sans-serif", letter: "'Fraunces', Georgia, serif",
      fx: ["#ff5c8a", "#ffc95e", "#c792ff", "#7fd1ff", "#ff8fb1", "#6fe0c0"],
      fonts: "family=Fraunces:opsz,wght@9..144,500;9..144,700&family=Great+Vibes&family=Outfit:wght@400;500;600",
    },
    fields: fields("recipient_name", "sender_name", "age", "letter", "reasons", "treats"),
    photos: PHOTOS,
    music: { default: "mus_warm_keys" },
    story: {
      opener: { kind: "gift", eyebrow: "Psst… someone made something for you", hint: "Tap the gift to open", sub: "Turn your sound on for the full surprise" },
      motif: "heart",
      ambient: { orbs: ["#ff5c8a", "#ffc95e", "#a98bff"], particles: "petals", colors: ["#ff8fb1", "#ffc95e", "#c792ff"] },
      chapters: [
        { type: "hero", kicker: "Happy Birthday", lead: "Today the stars, the balloons and I are all celebrating you.", floaters: "balloons", nameStyle: "script",
          wishes: ["A wish for you: more laughing until it hurts.", "May every song you love play at the right moment.", "Wish found: breakfast in bed, on me.", "A year of sunny mornings and slow evenings.", "May you always feel as loved as you are.", "Wish found: one very long hug from {{sender_name}}."] },
        { type: "question", eyebrow: "A serious question", title: "Do you love me?", lead: "Think carefully. There is only one correct answer, and the buttons know it.", yes: "Yes, obviously", no: ["No", "Are you sure?", "Think again", "Nice try", "Not an option"], done: "I knew it. Lots of love" },
        { type: "catch", eyebrow: "Catch my heart", title: "Catch 15 hearts in 20 seconds", lead: "Tap the falling hearts before they slip away. Golden ones count for three.", item: "heart", target: 15, seconds: 20, win: "You caught my heart", winSub: "Truth is, you had it all along.", lose: "So close!", loseSub: "You caught {caught}. My heart is a little slippery today." },
        { type: "slide", eyebrow: "A little puzzle", title: "Piece us back together", photo: 0, solved: "You complete me", solvedSub: "Solved in {moves} moves. Clever and beautiful, as always." },
        { type: "wheel", eyebrow: "Spin for a gift", title: "Spin the wheel of treats", lead: "You get three spins. Every treat you land on is yours to claim, any day you like.", spins: 3, field: "treats",
          items: ["Movie night", "Breakfast in bed", "A long drive", "Dessert date", "Foot massage", "You pick dinner", "Shopping trip", "Lazy Sunday"], done: "Screenshot these and claim them all" },
        { type: "gallery", eyebrow: "Us", title: "A few of my favourite moments", lead: "Every one of these is a reason I smile.", style: "polaroid" },
        { type: "flips", eyebrow: "Why you", title: "Six things I adore about you", lead: "Tap each card to flip it.", field: "reasons", items: REASONS },
        { type: "ritual", eyebrow: "Make a wish", title: "Close your eyes, make a wish…", lead: "…then tap each candle to blow it out.", kind: "candles", count: 5, done: "Your wish is on its way", again: "Light the candles again" },
        { type: "letter", eyebrow: "For you", title: "One last thing", lead: "I wrote you a letter. Tap to open it.", style: "envelope", field: "letter" },
        { type: "finale", eyebrow: "Grand finale", title: "One last surprise", lead: "Ready? Tap the button and look up.", button: "Light up the sky", headline: "Happy Birthday, {{recipient_name}}", signoff: "Made with all my love, by {{sender_name}}", effect: "fireworks" },
      ],
    },
  },

  /* 2 ─────────────────────────────── */
  {
    ...base,
    slug: "bday-royal-rose",
    name: "Royal Rose",
    description: "Rose gold and falling petals. Gilded photo frames, a memory game, a secret to scratch and a champagne toast.",
    traits: ["For a wife or husband", "Memory game", "Champagne toast", "Scratch-card secret"],
    priceMinor: 34900,
    theme: {
      bg: "#1a0910", fg: "#f7e6e1", muted: "#cfaeb0", line: "#3d1a26", card: "#26101a",
      accent: "#e8a598", accent2: "#b3264d", accent3: "#f3cf8e", onAccent: "#1a0910", paper: "#fbf3ee", paperInk: "#3b1620",
      display: "'Playfair Display', Georgia, serif", hand: "'Pinyon Script', cursive", body: "'Lato', system-ui, sans-serif", letter: "'Cormorant Garamond', Georgia, serif",
      fx: ["#e8a598", "#f3cf8e", "#b3264d", "#fbf3ee", "#d97a8c"],
      fonts: "family=Playfair+Display:wght@500;700&family=Pinyon+Script&family=Lato:wght@400;700&family=Cormorant+Garamond:ital,wght@0,500;1,500",
    },
    fields: fields("recipient_name", "sender_name", "age", "letter", "reasons", { key: "secret_line", label: "A secret for the scratch card", help: "A plan, a promise, or something you have never said." }),
    photos: PHOTOS,
    music: { default: "mus_warm_keys" },
    story: {
      opener: { kind: "envelope", eyebrow: "An invitation, sealed with love", hint: "Tap the seal to open", sub: "Sound on, please" },
      motif: "petal",
      ambient: { orbs: ["#b3264d", "#e8a598", "#f3cf8e"], particles: "petals", colors: ["#e8a598", "#b3264d", "#f3cf8e"] },
      chapters: [
        { type: "hero", kicker: "Happy Birthday, my love", lead: "Every year with you is my favourite year so far.", floaters: "balloons", nameStyle: "script",
          wishes: ["A rose for every year I have loved you.", "Wish found: a dance in the kitchen, no music needed.", "May this year be as gentle as you are.", "Wish found: a whole day where you do nothing at all.", "To more slow mornings, together.", "Wish found: {{sender_name}} does the dishes for a month."] },
        { type: "gallery", eyebrow: "Our gallery", title: "Portraits of us", lead: "Hung with care, like everything about you.", style: "frames" },
        { type: "question", eyebrow: "A small formality", title: "Will you be mine for another year?", lead: "I'm asking properly this time.", yes: "Always", no: ["Let me think", "Hmm…", "Wait", "Ask again", "I can't say no"], done: "Then it's settled. Forever it is" },
        { type: "flips", eyebrow: "Why you", title: "Reasons I'd choose you again", lead: "Tap a card. Then tap the next one.", field: "reasons", items: REASONS },
        { type: "memory", eyebrow: "Remember when", title: "Find the matching memories", lead: "Turn two cards at a time.", pairs: 4, done: "Every memory, matched" },
        { type: "scratch", eyebrow: "A secret", title: "Something I've been keeping", lead: "Scratch gently.", reveal: "{{secret_line}}", cover: "Scratch here" },
        { type: "ritual", eyebrow: "A toast", title: "To you, {{recipient_name}}", lead: "Tap the bottle to pop the champagne.", kind: "champagne", count: 1, done: "Cheers to you, my love", again: "Pour another" },
        { type: "letter", eyebrow: "For you", title: "My letter", lead: "Tap the seal to open it.", style: "envelope", field: "letter" },
        { type: "finale", eyebrow: "Grand finale", title: "One more thing", lead: "Ready?", button: "Light up the night", headline: "Happy Birthday, {{recipient_name}}", signoff: "Yours, always. {{sender_name}}", effect: "fireworks" },
      ],
    },
  },

  /* 3 ─────────────────────────────── */
  {
    ...base,
    slug: "bday-retro-arcade",
    name: "Retro Arcade",
    description: "Neon pixels and arcade sounds. Catch hearts for a high score, rebuild the level, spin for power-ups and launch rockets.",
    traits: ["For a brother or boyfriend", "Arcade catch game", "Power-up wheel", "Rocket launch"],
    priceMinor: 24900,
    theme: {
      bg: "#0a0a1f", fg: "#e8f1ff", muted: "#9aa7d1", line: "#23234d", card: "#13132e",
      accent: "#ff2e88", accent2: "#00e5ff", accent3: "#ffe600", onAccent: "#0a0a1f", paper: "#f2f2ff", paperInk: "#12122a",
      display: "'Press Start 2P', monospace", hand: "'Bungee', system-ui, sans-serif", body: "'Space Grotesk', system-ui, sans-serif", letter: "'VT323', monospace",
      fx: ["#ff2e88", "#00e5ff", "#ffe600", "#7b2cff", "#39ff14"],
      fonts: "family=Press+Start+2P&family=Bungee&family=Space+Grotesk:wght@400;500;600&family=VT323",
    },
    fields: fields("recipient_name", "sender_name", "age", { key: "letter", label: "Your message" }, "treats"),
    photos: PHOTOS,
    music: { default: "mus_hbd_box" },
    story: {
      opener: { kind: "chest", eyebrow: "A loot box has dropped", hint: "Tap to open the loot box", sub: "Sound on for the full game" },
      motif: "pixel",
      ambient: { orbs: ["#ff2e88", "#00e5ff", "#7b2cff"], particles: "stars", colors: ["#00e5ff", "#ff2e88", "#ffe600"] },
      chapters: [
        { type: "hero", kicker: "Player 1 · Level up", lead: "A new level just unlocked. Pop the balloons for bonus wishes.", floaters: "balloons", nameStyle: "pixel", showAge: true,
          wishes: ["+1 life: a year of good health.", "Bonus: unlimited snacks.", "Achievement unlocked: legend status.", "Power-up: luck +100.", "Secret level found: a surprise from {{sender_name}}.", "Combo! Double the cake."] },
        { type: "catch", eyebrow: "Bonus round", title: "Catch 20 hearts in 25 seconds", lead: "Golden hearts are worth three. Go for the high score.", item: "pixel", target: 20, seconds: 25, win: "High score!", winSub: "New record. Nobody can beat you.", lose: "Game over", loseSub: "Score: {caught}. Insert coin and try again." },
        { type: "question", eyebrow: "Boss question", title: "Who's the best player in the world?", lead: "Choose wisely.", yes: "{{recipient_name}}, obviously", no: ["Someone else", "Me?", "Error 404", "Nope", "Lag!"], done: "Correct answer. +1000 points" },
        { type: "slide", eyebrow: "Puzzle level", title: "Rebuild the level", photo: 0, solved: "Level complete", solvedSub: "{moves} moves. Speedrun material." },
        { type: "wheel", eyebrow: "Power-ups", title: "Spin for power-ups", lead: "Three spins. Every power-up is redeemable in real life.", spins: 3, field: "treats",
          items: ["Pizza night", "Game marathon", "Snack refill", "Free hug", "Movie pick", "No chores", "Ice cream", "Surprise"], done: "Inventory full. Redeem anytime" },
        { type: "gallery", eyebrow: "Replay", title: "Best moments, on repeat", lead: "Scroll the film.", style: "film" },
        { type: "ritual", eyebrow: "Launch sequence", title: "Launch the birthday rockets", lead: "Tap each rocket to launch it.", kind: "rockets", count: 5, done: "All rockets launched", again: "Reload rockets" },
        { type: "letter", eyebrow: "Incoming message", title: "You have 1 new message", lead: "Tap to open the file.", style: "terminal", field: "letter" },
        { type: "finale", eyebrow: "Final level", title: "Game complete", lead: "Press start.", button: "Press start", headline: "Happy Birthday, {{recipient_name}}", signoff: "Player 2: {{sender_name}}", effect: "fireworks" },
      ],
    },
  },

  /* 4 ─────────────────────────────── */
  {
    ...base,
    slug: "bday-ocean-sunset",
    name: "Ocean Sunset",
    description: "A sunset by the sea. Pop bubbles, catch seashells, match memories and find a message in a bottle.",
    traits: ["For anyone who loves the beach", "Seashell catch game", "Memory match", "Message in a bottle"],
    priceMinor: 24900,
    theme: {
      bg: "#0e2a47", fg: "#fff4e8", muted: "#bcd2e3", line: "#24476a", card: "#153a5c",
      accent: "#ff7e67", accent2: "#2ec4b6", accent3: "#ffd166", onAccent: "#0e2a47", paper: "#fff8ef", paperInk: "#1d3557",
      display: "'DM Serif Display', Georgia, serif", hand: "'Caveat', cursive", body: "'Nunito', system-ui, sans-serif", letter: "'Lora', Georgia, serif",
      fx: ["#ff7e67", "#2ec4b6", "#ffd166", "#bde0fe", "#ffafcc"],
      fonts: "family=DM+Serif+Display&family=Caveat:wght@500;700&family=Nunito:wght@400;600;700&family=Lora:ital@0;1",
    },
    fields: fields("recipient_name", "sender_name", "age", "letter", "reasons"),
    photos: PHOTOS,
    music: { default: "mus_warm_keys" },
    story: {
      opener: { kind: "chest", eyebrow: "The tide brought something for you", hint: "Tap the treasure chest", sub: "Sound on for the waves" },
      motif: "shell",
      backdrop: "linear-gradient(180deg, #0e2a47 0%, #15406a 60%, #3d4f7a 100%)",
      ambient: { orbs: ["#ff7e67", "#2ec4b6", "#ffd166"], particles: "bubbles", colors: ["#bde0fe", "#2ec4b6", "#ffffff"] },
      chapters: [
        { type: "hero", kicker: "Happy Birthday", lead: "The sun is setting just for you. Pop the bubbles for wishes from the sea.", floaters: "bubbles", nameStyle: "script",
          wishes: ["A wish from the sea: calm days and big adventures.", "May you always find your way back to the shore.", "Wish found: a beach trip, soon.", "A year as bright as this sunset.", "Wish found: ice cream that never melts.", "May every wave bring good news."] },
        { type: "catch", eyebrow: "Beachcombing", title: "Catch 15 seashells in 20 seconds", lead: "Golden shells count for three.", item: "shell", target: 15, seconds: 20, win: "What a collection!", winSub: "The sea likes you as much as I do.", lose: "The tide was faster", loseSub: "You found {caught}. Try again before the waves come back." },
        { type: "memory", eyebrow: "Shells and secrets", title: "Every shell hides a memory", lead: "Find the pairs.", pairs: 4, done: "All memories found" },
        { type: "gallery", eyebrow: "Postcards", title: "Postcards from our story", style: "polaroid" },
        { type: "flips", eyebrow: "Like the ocean", title: "Waves of reasons", lead: "Tap each card.", field: "reasons", items: REASONS },
        { type: "ritual", eyebrow: "Make a wish", title: "Send your wishes over the sea", lead: "Tap each lantern to let it go.", kind: "lanterns", count: 5, done: "Your wishes are sailing away", again: "Light more lanterns" },
        { type: "letter", eyebrow: "Washed ashore", title: "A message in a bottle", lead: "Tap the bottle to open it.", style: "bottle", field: "letter" },
        { type: "finale", eyebrow: "Grand finale", title: "Fireworks over the water", lead: "Look up.", button: "Light up the sky", headline: "Happy Birthday, {{recipient_name}}", signoff: "With love from {{sender_name}}", effect: "fireworks" },
      ],
    },
  },

  /* 5 ─────────────────────────────── */
  {
    ...base,
    slug: "bday-garden-bloom",
    name: "Garden Bloom",
    description: "A soft spring garden with butterflies. Photos, the things they taught you, a hidden note and a letter.",
    traits: ["For Mom", "Light and gentle", "Scratch-card note", "Memory match"],
    priceMinor: 24900,
    theme: {
      bg: "#fff8f1", fg: "#3e3a36", muted: "#6f655e", line: "#eadfd3", card: "#fdeee3",
      accent: "#c2547a", accent2: "#6f9473", accent3: "#c9822a", onAccent: "#ffffff", paper: "#ffffff", paperInk: "#3e3a36",
      display: "'Cormorant Garamond', Georgia, serif", hand: "'Dancing Script', cursive", body: "'Karla', system-ui, sans-serif", letter: "'Lora', Georgia, serif",
      fx: ["#f4a7b9", "#a8d5ba", "#c8b6e2", "#ffd6a5", "#c2547a"],
      fonts: "family=Cormorant+Garamond:wght@500;700&family=Dancing+Script:wght@500;700&family=Karla:wght@400;500;700&family=Lora:ital@0;1",
    },
    fields: fields("recipient_name", "sender_name", "age", "letter", { key: "reasons", label: "Things they taught you (one per line)" }, { key: "secret_line", label: "A note for the scratch card", help: "A thank-you, a plan, or a little surprise." }),
    photos: PHOTOS,
    music: { default: "mus_warm_keys" },
    story: {
      opener: { kind: "envelope", eyebrow: "A little something from the garden", hint: "Tap the envelope", sub: "Sound on, if you can" },
      motif: "butterfly",
      ambient: { orbs: ["#f4a7b9", "#a8d5ba", "#c8b6e2"], particles: "petals", colors: ["#f4a7b9", "#c8b6e2", "#a8d5ba"] },
      chapters: [
        { type: "hero", kicker: "Happy Birthday", lead: "Everything good in me started growing in your garden.", floaters: "balloons", nameStyle: "script",
          wishes: ["A wish for you: rest, and plenty of it.", "May your chai always be the perfect temperature.", "Wish found: a day where we do everything you like.", "May every flower you plant bloom twice.", "Wish found: a long call, no rushing.", "To a year as warm as your hugs."] },
        { type: "gallery", eyebrow: "Through the years", title: "Pressed like flowers", lead: "Some of my favourite moments with you.", style: "polaroid" },
        { type: "flips", eyebrow: "What you taught me", title: "Things I learned from you", lead: "Tap each card.", field: "reasons",
          items: ["To be kind first.", "That a hug fixes most things.", "How to make the best of very little.", "To stand up for what's right.", "That home is a person.", "To never skip breakfast."] },
        { type: "scratch", eyebrow: "A hidden note", title: "Something I want you to know", lead: "Scratch the card.", reveal: "{{secret_line}}", cover: "Scratch me" },
        { type: "memory", eyebrow: "Remember?", title: "Find the matching memories", lead: "Turn two cards at a time.", pairs: 4, done: "You remember everything" },
        { type: "ritual", eyebrow: "Make a wish", title: "Your cake is ready", lead: "Tap each candle to blow it out.", kind: "candles", count: 5, done: "May every wish come true", again: "Light them again" },
        { type: "letter", eyebrow: "For you", title: "A letter, just for you", lead: "Tap to open it.", style: "envelope", field: "letter" },
        { type: "finale", eyebrow: "The last bloom", title: "One more surprise", lead: "Tap the button.", button: "Let it bloom", headline: "Happy Birthday, {{recipient_name}}", signoff: "All my love, {{sender_name}}", effect: "confetti" },
      ],
    },
  },

  /* 6 ─────────────────────────────── */
  {
    ...base,
    slug: "bday-galaxy-quest",
    name: "Galaxy Quest",
    description: "A trip through space. Catch shooting stars, fix the photo puzzle, spin for galactic gifts and launch rockets.",
    traits: ["For dreamers and explorers", "Shooting-star game", "Rocket launch", "Transmission letter"],
    priceMinor: 29900,
    theme: {
      bg: "#050816", fg: "#e9ecff", muted: "#a9b0d9", line: "#1c2250", card: "#0c1130",
      accent: "#8f75ff", accent2: "#4cc9f0", accent3: "#ffd166", onAccent: "#050816", paper: "#f4f3ff", paperInk: "#1a1446",
      display: "'Orbitron', system-ui, sans-serif", hand: "'Sacramento', cursive", body: "'Exo 2', system-ui, sans-serif", letter: "'Exo 2', system-ui, sans-serif",
      fx: ["#8f75ff", "#4cc9f0", "#ffd166", "#f72585", "#ffffff"],
      fonts: "family=Orbitron:wght@500;700&family=Sacramento&family=Exo+2:wght@400;500;600",
    },
    fields: fields("recipient_name", "sender_name", "age", { key: "letter", label: "Your message" }, "treats"),
    photos: PHOTOS,
    music: { default: "mus_warm_keys" },
    story: {
      opener: { kind: "gift", eyebrow: "A parcel arrived from deep space", hint: "Tap to open the parcel", sub: "Sound on for the full voyage" },
      motif: "star",
      ambient: { orbs: ["#7b5cff", "#4cc9f0", "#f72585"], particles: "stars", colors: ["#ffffff", "#4cc9f0", "#ffd166"] },
      chapters: [
        { type: "hero", kicker: "Happy Birthday, Commander", lead: "The whole galaxy lined up to say it. Pop the planets for messages from space.", floaters: "bubbles", nameStyle: "display", showAge: true,
          wishes: ["Signal received: you are out of this world.", "May your year orbit around good things.", "Wish found: a night of stargazing together.", "Mission: make this your best year yet.", "The universe agrees: you're a star.", "Wish found: zero gravity, zero stress."] },
        { type: "catch", eyebrow: "Star shower", title: "Catch 15 shooting stars", lead: "20 seconds. Golden stars count for three.", item: "star", target: 15, seconds: 20, win: "Wishes collected!", winSub: "Every one of them is for you.", lose: "They're fast!", loseSub: "You caught {caught}. The sky will send more." },
        { type: "slide", eyebrow: "Repair mission", title: "Fix the broken transmission", photo: 0, solved: "Signal restored", solvedSub: "Repaired in {moves} moves. Houston is impressed." },
        { type: "wheel", eyebrow: "Galactic gifts", title: "Spin the planet wheel", lead: "Three spins. Every gift lands on Earth soon.", spins: 3, field: "treats",
          items: ["Stargazing night", "Planetarium trip", "Space movie", "Favourite meal", "A whole lazy day", "Ice cream", "Road trip", "Surprise"], done: "Gifts received. Claim them anytime" },
        { type: "gallery", eyebrow: "Mission log", title: "Recorded memories", style: "film" },
        { type: "ritual", eyebrow: "Liftoff", title: "Launch the birthday rockets", lead: "Tap each rocket.", kind: "rockets", count: 5, done: "To infinity, and your birthday", again: "Refuel" },
        { type: "letter", eyebrow: "Incoming transmission", title: "A message from Earth", lead: "Tap to decode it.", style: "terminal", field: "letter" },
        { type: "finale", eyebrow: "Grand finale", title: "Supernova", lead: "Ready for the big one?", button: "Trigger the supernova", headline: "Happy Birthday, {{recipient_name}}", signoff: "From your mission partner, {{sender_name}}", effect: "fireworks" },
      ],
    },
  },

  /* 7 ─────────────────────────────── */
  {
    ...base,
    slug: "bday-desi-dhamaka",
    name: "Desi Dhamaka",
    description: "Marigolds, lanterns and full Bollywood energy. A cheeky question, a marigold game, a treat wheel and diyas to light.",
    traits: ["For family and friends", "Marigold catch game", "Treat wheel", "Light the diyas"],
    priceMinor: 29900,
    theme: {
      bg: "#2b0a14", fg: "#fff1dc", muted: "#e3c3a6", line: "#4e1a2a", card: "#3a1020",
      accent: "#ff9f1c", accent2: "#e0218a", accent3: "#ffd166", onAccent: "#2b0a14", paper: "#fff6e5", paperInk: "#4a1224",
      display: "'Yeseva One', Georgia, serif", hand: "'Kaushan Script', cursive", body: "'Poppins', system-ui, sans-serif", letter: "'Lora', Georgia, serif",
      fx: ["#ff9f1c", "#e0218a", "#ffd166", "#2ec4b6", "#ff6b35"],
      fonts: "family=Yeseva+One&family=Kaushan+Script&family=Poppins:wght@400;500;600&family=Lora:ital@0;1",
    },
    fields: fields("recipient_name", "sender_name", "age", "letter", "treats", { key: "secret_line", label: "A secret for the scratch card", help: "A plan, a party, or a promise." }),
    photos: PHOTOS,
    music: { default: "mus_hbd_box" },
    story: {
      opener: { kind: "gift", eyebrow: "Arre! Someone sent you something", hint: "Tap to open your gift", sub: "Volume up, it's a celebration" },
      motif: "marigold",
      ambient: { orbs: ["#e0218a", "#ff9f1c", "#ffd166"], particles: "petals", colors: ["#ff9f1c", "#ffd166", "#e0218a"] },
      chapters: [
        { type: "hero", kicker: "Janamdin Mubarak", lead: "Today is not a day, it's a festival. Pop the lanterns for blessings.", floaters: "lanterns", nameStyle: "script",
          wishes: ["Ashirwad: a year full of happiness and good health.", "Wish found: unlimited gol gappe.", "May your life be a superhit, every Friday.", "Wish found: no work calls on your birthday.", "Blessing: mithai that never runs out.", "Wish found: a dance party, hosted by {{sender_name}}."] },
        { type: "question", eyebrow: "A serious question", title: "Who is the star of the family?", lead: "Only one right answer.", yes: "{{recipient_name}}, who else!", no: ["Sharma ji's son", "Main?", "Pakka?", "Not possible", "Try again"], done: "Correct! Superstar" },
        { type: "catch", eyebrow: "Marigold rain", title: "Catch 15 marigolds", lead: "20 seconds. Golden ones count for three.", item: "marigold", target: 15, seconds: 20, win: "Garland complete!", winSub: "Ready for the celebration.", lose: "Arre, so close!", loseSub: "You caught {caught}. One more try?" },
        { type: "scratch", eyebrow: "Surprise", title: "Ek secret hai", lead: "Scratch to reveal.", reveal: "{{secret_line}}", cover: "Scratch karo" },
        { type: "wheel", eyebrow: "Treat time", title: "Spin the treat wheel", lead: "Three spins. Treats are on {{sender_name}}.", spins: 3, field: "treats",
          items: ["Gol gappe party", "Shopping trip", "Chai date", "Movie night", "Mithai box", "Long drive", "Lazy Sunday", "Dance party"], done: "Screenshot karo, claim karo" },
        { type: "gallery", eyebrow: "Yaadein", title: "Our filmy moments", style: "polaroid" },
        { type: "ritual", eyebrow: "Roshni", title: "Light the diyas", lead: "Tap each diya to light it.", kind: "diyas", count: 7, done: "May your life always shine this bright", again: "Light them again" },
        { type: "letter", eyebrow: "Dil se", title: "A letter, from the heart", lead: "Tap to open it.", style: "envelope", field: "letter" },
        { type: "finale", eyebrow: "Grand finale", title: "Picture abhi baaki hai", lead: "Ready for the fireworks?", button: "Phatake chalao", headline: "Happy Birthday, {{recipient_name}}", signoff: "With lots of love, {{sender_name}}", effect: "fireworks" },
      ],
    },
  },

  /* 8 ─────────────────────────────── */
  {
    ...base,
    slug: "bday-candy-land",
    name: "Candy Land",
    description: "Bright, sweet and silly. Catch candies, match photos, fix the puzzle, spin for treats and blow out the candles.",
    traits: ["For kids", "Candy catch game", "Memory match", "Treat wheel"],
    priceMinor: 19900,
    theme: {
      bg: "#fff0f7", fg: "#3b2340", muted: "#6e4f72", line: "#f6d6e8", card: "#ffe2f0",
      accent: "#d42a7e", accent2: "#1fa784", accent3: "#e38b00", onAccent: "#ffffff", paper: "#ffffff", paperInk: "#3b2340",
      display: "'Fredoka', system-ui, sans-serif", hand: "'Pacifico', cursive", body: "'Nunito', system-ui, sans-serif", letter: "'Nunito', system-ui, sans-serif",
      fx: ["#ff4fa3", "#36c9a0", "#ffb703", "#4dabf7", "#9b5de5"],
      fonts: "family=Fredoka:wght@500;700&family=Pacifico&family=Nunito:wght@400;600;700",
    },
    fields: fields("recipient_name", "sender_name", "age", { key: "letter", label: "Your message", max: 700 }, "treats"),
    photos: PHOTOS,
    music: { default: "mus_hbd_box" },
    story: {
      opener: { kind: "gift", eyebrow: "Yay! A present for you", hint: "Tap the present!", sub: "Turn the sound on" },
      motif: "candy",
      ambient: { orbs: ["#ff9ecd", "#9be7d0", "#ffd88a"], particles: "confetti", colors: ["#ff4fa3", "#36c9a0", "#ffb703", "#4dabf7"] },
      chapters: [
        { type: "hero", kicker: "Happy Birthday", lead: "It's your special day! Pop all the balloons.", floaters: "balloons", nameStyle: "display", showAge: true,
          wishes: ["Yay! Extra cake for you!", "Wish found: a giant ice cream.", "You are super awesome!", "Wish found: a day at the park.", "Hooray! Presents are coming!", "Wish found: a big hug from {{sender_name}}."] },
        { type: "catch", eyebrow: "Candy rain", title: "Catch 15 candies", lead: "Tap them fast! Golden candies count for three.", item: "candy", target: 15, seconds: 25, win: "Sweet!", winSub: "You are the candy champion!", lose: "Oops!", loseSub: "You caught {caught}. Try again!" },
        { type: "memory", eyebrow: "Match game", title: "Find the pairs", lead: "Turn two cards at a time.", pairs: 3, done: "You did it!" },
        { type: "slide", eyebrow: "Puzzle", title: "Fix the picture", photo: 0, solved: "Super smart!", solvedSub: "Done in {moves} moves." },
        { type: "wheel", eyebrow: "Treat wheel", title: "Spin for treats", lead: "Three spins!", spins: 3, field: "treats",
          items: ["Ice cream", "Cartoon time", "Pizza party", "Toy shop trip", "Bedtime story", "Park day", "Cupcakes", "Pillow fort"], done: "Treats unlocked!" },
        { type: "gallery", eyebrow: "Look at you", title: "Our favourite pictures", style: "polaroid" },
        { type: "ritual", eyebrow: "Cake time", title: "Make a wish!", lead: "Tap the candles to blow them out.", kind: "candles", count: 5, done: "Happy birthday to you!", again: "Again!" },
        { type: "letter", eyebrow: "A note for you", title: "Read your message", lead: "Tap the envelope.", style: "envelope", field: "letter" },
        { type: "finale", eyebrow: "Party time", title: "The big surprise", lead: "Ready?", button: "Party time!", headline: "Happy Birthday, {{recipient_name}}!", signoff: "Love, {{sender_name}}", effect: "confetti" },
      ],
    },
  },

  /* 9 ─────────────────────────────── */
  {
    ...base,
    slug: "bday-golden-gala",
    name: "Golden Gala",
    description: "Black tie and gold. For milestone birthdays: gilded portraits, what makes them legendary, a secret and a champagne toast.",
    traits: ["For a milestone (30, 50…) or Dad", "Gilded portraits", "Champagne toast", "Gift wheel"],
    priceMinor: 34900,
    theme: {
      bg: "#0d0d0d", fg: "#f5ecd7", muted: "#c4b89f", line: "#2b2620", card: "#171512",
      accent: "#d4af37", accent2: "#a07c43", accent3: "#f7e7ce", onAccent: "#111111", paper: "#fbf6ea", paperInk: "#2a2418",
      display: "'Cinzel', Georgia, serif", hand: "'Alex Brush', cursive", body: "'Jost', system-ui, sans-serif", letter: "'Cormorant Garamond', Georgia, serif",
      fx: ["#d4af37", "#f7e7ce", "#a07c43", "#ffffff", "#e8c766"],
      fonts: "family=Cinzel:wght@500;700&family=Alex+Brush&family=Jost:wght@400;500;600&family=Cormorant+Garamond:ital,wght@0,500;1,500",
    },
    fields: fields("recipient_name", "sender_name", "age", "letter", { key: "reasons", label: "What makes them legendary (one per line)" }, "treats", { key: "secret_line", label: "A secret for the scratch card" }),
    photos: PHOTOS,
    music: { default: "mus_warm_keys" },
    story: {
      opener: { kind: "envelope", eyebrow: "You are cordially invited", hint: "Break the seal", sub: "Sound on for the full evening" },
      motif: "sparkle",
      ambient: { orbs: ["#d4af37", "#7a5c1e", "#f7e7ce"], particles: "sparks", colors: ["#d4af37", "#f7e7ce"] },
      chapters: [
        { type: "hero", kicker: "Happy Birthday", lead: "An evening in honour of a legend.", floaters: "balloons", nameStyle: "display", showAge: true,
          wishes: ["A toast: to many more golden years.", "Wish found: a dinner to remember.", "To a year of fine things and finer company.", "Wish found: a weekend away, all planned.", "May every chapter be better than the last.", "Wish found: a standing ovation, from {{sender_name}}."] },
        { type: "gallery", eyebrow: "The portrait hall", title: "The legend, in pictures", style: "frames" },
        { type: "flips", eyebrow: "The legend", title: "What makes you legendary", lead: "Tap each card.", field: "reasons",
          items: ["Your stories are the best at every table.", "You make everyone feel welcome.", "You've never once given up.", "Your laugh fills a room.", "You show up, every time.", "You make getting older look good."] },
        { type: "wheel", eyebrow: "Gifts of the evening", title: "Spin the gold wheel", lead: "Three spins. Every prize is real.", spins: 3, field: "treats",
          items: ["Fine dinner", "Spa day", "Weekend away", "Concert night", "Breakfast in bed", "Day off", "Shopping spree", "Surprise"], done: "Prizes reserved in your name" },
        { type: "scratch", eyebrow: "Sealed", title: "A secret, for your eyes only", lead: "Scratch the gold.", reveal: "{{secret_line}}", cover: "Scratch the gold" },
        { type: "ritual", eyebrow: "A toast", title: "Raise a glass", lead: "Tap the bottle to pop the champagne.", kind: "champagne", count: 1, done: "To you. Cheers!", again: "Another toast" },
        { type: "letter", eyebrow: "A speech", title: "A few words for you", lead: "Tap the seal.", style: "envelope", field: "letter" },
        { type: "finale", eyebrow: "Grand finale", title: "The final toast", lead: "Ready?", button: "Light up the evening", headline: "Happy Birthday, {{recipient_name}}", signoff: "Raised in your honour by {{sender_name}}", effect: "fireworks" },
      ],
    },
  },

  /* 10 ─────────────────────────────── */
  {
    ...base,
    slug: "bday-vintage-scrapbook",
    name: "Vintage Scrapbook",
    description: "A handmade scrapbook. Taped photos, a cheeky question, a memory game, inside jokes and a typewritten letter.",
    traits: ["For a best friend", "Scrapbook photos", "Memory game", "Typewriter letter"],
    priceMinor: 24900,
    theme: {
      bg: "#efe4d2", fg: "#3b2f2f", muted: "#66574b", line: "#d9c8ae", card: "#f7efe2",
      accent: "#b23a2c", accent2: "#2f6f73", accent3: "#a8701a", onAccent: "#ffffff", paper: "#fffaf0", paperInk: "#3b2f2f",
      display: "'Libre Baskerville', Georgia, serif", hand: "'Homemade Apple', cursive", body: "'Work Sans', system-ui, sans-serif", letter: "'Special Elite', 'Courier New', monospace",
      fx: ["#c0392b", "#2f6f73", "#e1a730", "#8e6c8a", "#3b2f2f"],
      fonts: "family=Libre+Baskerville:wght@400;700&family=Homemade+Apple&family=Work+Sans:wght@400;500;600&family=Special+Elite",
    },
    fields: fields("recipient_name", "sender_name", "age", "letter", { key: "reasons", label: "Things only you two understand (one per line)" }, { key: "secret_line", label: "An inside joke for the scratch card" }),
    photos: PHOTOS,
    music: { default: "mus_warm_keys" },
    story: {
      opener: { kind: "envelope", eyebrow: "Something came in the post", hint: "Tap to open the envelope", sub: "Sound on" },
      motif: "star",
      ambient: { orbs: ["#e1a730", "#c0392b", "#2f6f73"], particles: "confetti", colors: ["#c0392b", "#2f6f73", "#e1a730"] },
      chapters: [
        { type: "hero", kicker: "Happy Birthday", lead: "A scrapbook of us, made by hand, just for you.", floaters: "balloons", nameStyle: "script",
          wishes: ["Wish found: another year of terrible jokes.", "Gold star for surviving me another year.", "Wish found: a trip we actually take.", "May your playlists always slap.", "Wish found: snacks, on {{sender_name}}.", "To more 2 a.m. conversations."] },
        { type: "gallery", eyebrow: "Page one", title: "Exhibit A: us", style: "polaroid", captions: ["Classic us", "No regrets", "This day!", "Iconic", "Legends", "Never again (again)", "Best day", "Us, always"] },
        { type: "question", eyebrow: "Pop quiz", title: "Who's the funniest person you know?", lead: "Be honest.", yes: "{{sender_name}}, obviously", no: ["Me", "Hmm", "Nope", "Wrong", "Try again"], done: "Correct. Gold star for you" },
        { type: "memory", eyebrow: "Page two", title: "Match our moments", lead: "Turn two cards at a time.", pairs: 4, done: "Memory of an elephant" },
        { type: "slide", eyebrow: "Page three", title: "Tape us back together", photo: 1, solved: "Good as new", solvedSub: "{moves} moves. Arts and crafts champion." },
        { type: "flips", eyebrow: "Inside jokes", title: "Things only we understand", lead: "Tap each card.", field: "reasons",
          items: ["That one time. You know the one.", "The snack-sharing rules.", "Our secret handshake.", "Why we can't go back to that café.", "The voice notes that should never leak.", "Laughing before the joke ends."] },
        { type: "scratch", eyebrow: "Classified", title: "Top secret", lead: "Scratch to reveal.", reveal: "{{secret_line}}", cover: "Classified" },
        { type: "letter", eyebrow: "The last page", title: "A typewritten letter", lead: "Tap to open it.", style: "envelope", field: "letter" },
        { type: "finale", eyebrow: "The end (not really)", title: "One last page", lead: "Ready?", button: "Throw the confetti", headline: "Happy Birthday, {{recipient_name}}", signoff: "Your partner in crime, {{sender_name}}", effect: "confetti" },
      ],
    },
  },
];
